GenomicMedLab/software-templates

- python/{{cookiecutter.project_slug}}/pyproject.toml
Ran through a few projects as testbeds for the ruff rules and found a few tweaks that we should make. Calling this "priority:high" because this repo is sort of acting as a source of truth for other repos (and it's a small fix).
> cicd: ignore assert check in tests

- .github/workflows/stale.yml
close #12 . https://github.com/actions/stale . We will need to add a `stale` labels to all of our repos.
* Comments on stale issues and PRs
> cicd: add stale bot

- python/{{cookiecutter.project_slug}}/pyproject.toml
Previously, the docs config is only ignored for linting. This moves it up to be ignored when formatting, also.
I think this was just been an oversight from when the Ruff config rules got restructured.
> style: exclude docs config for format and lint

- python/{{cookiecutter.project_slug}}/.github/workflows/pr-priority-label.yaml
This was added to the repo root, but not to the cookiecutter template itself -- this PR adds it to the template, as well (and we can copy out from there)
> cicd(python): add priority label PR action

- python/{{cookiecutter.project_slug}}/.github/workflows/checks.yaml
I figured this out too late, but there's a built-in token with sufficient permissions to support the test for building the autochangelog from GitHub releases. This PR uses it.
> cicd(python): use GITHUB_TOKEN for changelog permissions

- python/{{cookiecutter.project_slug}}/.github/workflows/checks.yaml
- python/{{cookiecutter.project_slug}}/pyproject.toml
* Reflect Biocommons policy of supporting the three most recent full Python releases. Lets us take advantage of some recent features, including some nicer type annotation syntax.
* Will entail some minor work implementing new [pyupgrade](https://docs.astral.sh/ruff/rules/#pyupgrade-up) linter rules exposed by moving the `requires-python` setting up
* Suggested by @korikuzma somewhere (Slack?)
> feat(python): move support to >=3.10

- python/{{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/bug-report.yaml
- python/{{cookiecutter.project_slug}}/.github/ISSUE_TEMPLATE/feature-request.yaml
These issue templates exist in this repo, but this issue adds them to the cookiecutter template that creates new Python projects also
> feat(python): add issue templates

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
I think this is good for outside collaborators for our open-source projects, but don't think it should be required
> chore: make contribution optional in issue templates

- .github/workflows/update-python.yaml
I missed this when doing the 3.10 update
> cicd: update min required python version

- python/{{cookiecutter.project_slug}}/pyproject.toml
close #16 
* simplifies release workflow: rather than maintaining both a `version.py` file and a git tag for the release, the installed package gets its version number directly from the git tag
* one less file
* clarifies version metadata for in-progress releases because they get a giant commit hash at the end of them 
outstanding issue: entails some changes to our version patterns and behavior, discuss in https://github.com/GenomicMedLab/wagner-lab-issues/discussions/28. I think this also sets us up to move towards semantic release/release please, although we probably still have some steps to get there.
> build(python): use setuptools-scm

- .github/workflows/checks.yaml
- python/{{cookiecutter.project_slug}}/.github/workflows/checks.yaml
- python/{{cookiecutter.project_slug}}/.github/workflows/release.yaml
Two things (so no squash)
* update action versions for python template
* update an older action version for the template repo itself
> Update GH Action versions

- python/{{cookiecutter.project_slug}}/.pre-commit-config.yaml
Or else we get the following:
```
No AWS keys were found in the configured credential files and environment variables.
Please ensure you have the correct setting for --credentials-file
```
> fix(pre-commit): add --allow-missing-credentials arg

- .github/workflows/update-python.yaml
- python/{{cookiecutter.project_slug}}/.pre-commit-config.yaml
I thiiiiink this is correct
I am also increasingly of the opinion that this special Ruff hook might be more trouble than it's worth, there's a way to define a custom hook that might make more sense, and would rely on the environment's ruff rather than a special precommit-only ruff
> fix(cicd): generate correctly formatted ruff value for precommit

- python/{{cookiecutter.project_slug}}/pyproject.toml
Pytest functions really don't need docstrings in the sense that you never actually call those functions... if we want to add extra details using the docstring space, that's fine, but I don't think it should be required for every test
> feat(python): ignore doc requirements in tests

- python/{{cookiecutter.project_slug}}/.github/workflows/stale.yaml
I think this was fixed in most repos but missed in the template.
> fix(python): use rev tag for workflow ref

- python/{{cookiecutter.project_slug}}/tests/conftest.py
Motivated by two things
* the "noisy logs" thing really is annoying in a lot of our stuff and it'd be nice to have the code there to handle it. Easy to delete where it's really unnecessary
* I wanted to add a set of tests to the FastAPI branch I'm working on, but the template doesn't currently include any tests by default, so I wanted to have a little bit of a skeleton there.
> feat(python): add conftest.py

- .github/workflows/update-python.yaml
- python/{{cookiecutter.project_slug}}/pyproject.toml
* Use correct pattern for precommit version update
* Merge precommit and precommit-hooks jobs
* Use built-in precommit autoupdater to update hooks
* Gracefully handle case where no update is needed
> cicd: fix precommit autoupdate job

- python/cookiecutter.json
- python/hooks/post_gen_project.py
- python/{{cookiecutter.project_slug}}/pyproject.toml
- python/{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/__init__.py
- python/{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/api.py
- python/{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/config.py
- python/{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/logging.py
- python/{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/models.py
- python/{{cookiecutter.project_slug}}/tests/conftest.py
- python/{{cookiecutter.project_slug}}/tests/test_api.py
- requirements.txt
close #75 
this became much bigger than planned, but it reflects a few aspirations for what a service-like application should probably look like
* FastAPI `api.py` module, including a `/service_info` endpoint conforming to the GA4GH spec. I didn't bother implementing `updatedAt` (it's optional) because I think it'd be kind of a hassle to update a datetime object every time we make a release. Maybe there's a way to automate this but not a priority IMO.
* An API tests module with reasonable coverage
* A library config module. I don't think we have any services right now that *quite* map to the dev/test/staging/prod schema (I took this from rails), but some are pretty close and we could tweak as needed. The idea here is that it's a central source of truth about what kind of an environment …
> feat: add fastapi + service_info endpoint

- python/cookiecutter.json
- python/hooks/post_gen_project.py
- python/{{cookiecutter.project_slug}}/docs/source/cli_reference.rst
- python/{{cookiecutter.project_slug}}/docs/source/conf.py
- python/{{cookiecutter.project_slug}}/docs/source/index.rst
- python/{{cookiecutter.project_slug}}/pyproject.toml
- python/{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/cli.py
- python/{{cookiecutter.project_slug}}/src/{{cookiecutter.project_slug}}/logging.py
> feat(python): add CLI option

- python/{{cookiecutter.project_slug}}/.gitignore
> chore(python): add uv.lock to .gitignore

- python/{{cookiecutter.project_slug}}/pyproject.toml
close #111
I think `fastapi dev path/to/my/api.py` is a bit more readable for activity monitoring/debugging than the uvicorn builtin printing
> feat(python): add fastapi CLI
